# -*- coding: utf-8 -*-
"""Get It Done

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vBKPyB0_7OWBTHNk5E75UaCxWwTP2NJM
"""

!git clone https://github.com/AlexeyAB/darknet

# Commented out IPython magic to ensure Python compatibility.
# %cd darknet
!sed -i 's/OPENCV=0/OPENCV=1/' Makefile
!sed -i 's/GPU=0/GPU=1/' Makefile
!sed -i 's/CUDNN=0/CUDNN=1/' Makefile
!sed -i 's/CUDNN_HALF=0/CUDNN_HALF=1/' Makefile

!make

# Commented out IPython magic to ensure Python compatibility.
def imShow(path):
  import cv2
  import matplotlib.pyplot as plt
#   %matplotlib inline

  image = cv2.imread(path)
  height, width = image.shape[:2]
  resized_image = cv2.resize(image,(3*width, 3*height), interpolation = cv2.INTER_CUBIC)

  fig = plt.gcf()
  fig.set_size_inches(18, 10)
  plt.axis("off")
  plt.imshow(cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB))
  plt.show()

def upload():
  from google.colab import files
  uploaded = files.upload() 
  for name, data in uploaded.items():
    with open(name, 'wb') as f:
      f.write(data)
      print ('saved file', name)
  
def download(path):
  from google.colab import files
  files.download(path)

# Commented out IPython magic to ensure Python compatibility.
# %cd ..
from google.colab import drive
drive.mount('/content/gdrive')

!ln -s /content/gdrive/My\ Drive/ /mydrive

# Commented out IPython magic to ensure Python compatibility.
# %cd darknet

!cp /mydrive/GetItDone/obj.zip ../

!unzip ../obj.zip -d /content/darknet/data

!cp /mydrive/GetItDone/yolov4-obj.cfg ./cfg

!cp /mydrive/GetItDone/obj.names ./data
!cp /mydrive/GetItDone/obj.data  ./data

!cp /mydrive/GetItDone/generate_train.py ./

!python generate_train.py

!wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.conv.137

# %%capture
#!./darknet detector train data/obj.data cfg/yolov4-obj.cfg yolov4.conv.137 -dont_show

!./darknet detector train data/obj.data cfg/yolov4-obj.cfg /mydrive/GetItDone/backup/yolov4-obj_last.weights -dont_show

!./darknet detector map data/obj.data cfg/yolov4-obj.cfg /mydrive/GetItDone/backup/yolov4-obj_2000.weights

# Commented out IPython magic to ensure Python compatibility.
#  %cd cfg
!sed -i 's/batch=64/batch=1/' yolov4-obj.cfg
!sed -i 's/subdivisions=16/subdivisions=1/' yolov4-obj.cfg
# %cd ..

!./darknet detector demo data/obj.data cfg/yolov4-obj.cfg /mydrive/prv_cone/backup/yolov4-obj_6000.weights -dont_show /mydrive/prv_cone/test/test3.mp4 -thresh 0.5 -i 0 -out_filename /mydrive/prv_cone/Results/results_1_6000.avi

!./darknet detector test data/obj.data cfg/yolov4-obj.cfg /mydrive/GetItDone/backup/yolov4-obj_2000.weights /content/test1.jpg -thresh 0.6
imShow('predictions.jpg')

!./darknet detector test data/obj.data cfg/yolov4-obj.cfg /mydrive/GetItDone/backup/yolov4-obj_2000.weights /content/test4.jpg -thresh 0.95
imShow('predictions.jpg')